version: '3.8'

services:

  redis-cache:
    image: redis:7-alpine
    container_name: ticketflow_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ticketflow_network

  auth-service:
    build: ./auth-service
    container_name: ticketflow_auth
    ports:
      - "8000:8000"
    env_file:
      - ./auth-service/.env
    networks:
      - ticketflow_network

  booking-service:
    build: ./booking-service
    container_name: ticketflow_booking
    ports:
      - "8001:8001"
    env_file:
      - ./booking-service/.env
    environment:
      - REDIS_URL=redis://redis-cache:6379
    depends_on:
      - redis-cache
    networks:
      - ticketflow_network

  notification-service:
    build: ./notification-service
    container_name: ticketflow_notifications
    environment:
      - REDIS_URL=redis://redis-cache:6379
    depends_on:
      - redis-cache
    networks:
      - ticketflow_network

volumes:
  redis_data:

networks:
  ticketflow_network:
    driver: bridge